/**
 * Countries that are available for shipping.
 */
export enum Country {
  Austria = 'Austria',
  Belgium = 'Belgium',
  Bulgaria = 'Bulgaria',
  Canada = 'Canada',
  Croatia = 'Croatia',
  Cyprus = 'Cyprus',
  CzechRepublic = 'CzechRepublic',
  Denmark = 'Denmark',
  Estonia = 'Estonia',
  Finland = 'Finland',
  France = 'France',
  Germany = 'Germany',
  Greece = 'Greece',
  Hungary = 'Hungary',
  Ireland = 'Ireland',
  Italy = 'Italy',
  Japan = 'Japan',
  Latvia = 'Latvia',
  Lithuania = 'Lithuania',
  Luxembourg = 'Luxembourg',
  Malta = 'Malta',
  Netherlands = 'Netherlands',
  Poland = 'Poland',
  Portugal = 'Portugal',
  Romania = 'Romania',
  Slovakia = 'Slovakia',
  Slovenia = 'Slovenia',
  Spain = 'Spain',
  Sweden = 'Sweden',
  UnitedKingdom = 'UnitedKingdom',
  UnitedStates = 'UnitedStates',
}
